[package]
name = "bied"
version = "0.1.0"
authors = ["Soeking <great.from.g@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termion = "1.5.5"